.\" Manpage for rocket-depot.
.TH rocket-depot 1 "11 March 2016" "1.0.0" "rocket-depot man page"
.SH NAME
rocket-depot \- GTK+ 3 rdesktop/xfreerdp frontend
.SH SYNOPSIS
rocket-depot [OPTION]
.SH DESCRIPTION
Rocket Depot is a simple graphical frontend for rdesktop and FreeRDP with
support for connection profiles.  It runs on Linux desktops using GTK and takes
advantage of modern desktop environment features such as Unity Quicklists.
.SH OPTIONS
\fB\-\-help     print help options
.RE
.RS 7
.PP
\fB\-\-debug    print debugging output
.SH BUGS
https://github.com/robled/rocket-depot/issues
.SH AUTHOR
David Roble (robled@electronsweatshop.com)
